### ISSUE TITLE
Endless spinner on txn error with no escape 

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#100]
![image](https://user-images.githubusercontent.com/54227730/120397151-9f8fbd80-c2ec-11eb-8271-111578210360.png)

- [ ] Add guidance copy if wallet is stuck
- [ ] Restyling buttons on tx modal to match app (note the ones when txs are canceled)
- [ ] Inform user that they still need to allocate votes if 3rd tx was canceled

**Comment by samajammin** [comment]
It _appears_ the contribution tx actually succeeded - the UI just error'd out after.

**Comment by ryancreatescopy** [comment]
I added a close button to one of these modals in one of my PRs but yeah I don't know if this modal should be closable as it might make the tx very confusing. Perhaps just an error if something is timing out?

**Comment by wackerow** [comment]
So I do see the downside to having a way to exit here, and tend to agree an error/warning would be more appropriate.

Perhaps some small text that appears at the bottom of this modal after maybe 5-10 seconds that states
"If you have been waiting a while, consider refreshing your browser and reconnect your wallet."

A couple things I noted while looking at this again:
- If you cancel any of the transaction steps, the button to escape needs restyling to match app
- On initial contribution, if user cancels the 3rd tx, the votes are not recorded but it UI displays as though the user has contributed to those projects. They are able to "reallocate" which would actually be the first allocation... the UI should reflect that the user still needs to allocate their project votes or the funds will end up in the matching pool

**Comment by wackerow** [comment]
cc: @corwintines @pettinarip @samajammin

**Comment by samajammin** [comment]
@pettinarip let's go with Paul's suggestion (slight copy tweak):
```
If you have been waiting a while, consider refreshing your browser and reconnecting your wallet.
```
