### ISSUE TITLE
Reallocation button only active if cart changes

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#102]
![image](https://user-images.githubusercontent.com/40891631/120453077-a0772c80-c38a-11eb-9fce-c78bf8f862b2.png)

Currently the reallocation button is active even if nothing has changed... let's disable the button if state of local cart is the same as the state of the on-chain contributions.

**Comment by samajammin** [comment]
This will involve comparing the local app state of the cart to the smart contract state of the user's contribution.

**Comment by samajammin** [comment]
@corwintines FYI this might be worth considering how we implement the committed cart vs. the local state cart. Not sure if this requires us to add some `isDirty` prop to the cart to track if local changes have been made that differ from the commited cart state.

**Comment by samajammin** [comment]
Confirming this is still an issue:

https://user-images.githubusercontent.com/8097623/122656635-4b207680-d111-11eb-84a7-dbe6bd3a5853.mp4
