### ISSUE TITLE
Cart reallocation: update header designs

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#103]
Edit: see latest comment for designs

**Comment by samajammin** [comment]
@ryancreatescopy so no "remove all" button when in reallocation?

**Comment by ryancreatescopy** [comment]
Think we need to go through this together based on the logic around new/old projects you were mentioning. There will be a remove all option in the `...` more button at the top... but need to solidify thinking around this when I know more about your implementation proposal.

**Comment by ryancreatescopy** [comment]
Clarification on cart design for titles/actions e.g. "Your contributions", smart actions and edit buttons

From left to right: contribution, reallocation (readonly), reallocation (edit)
![image](https://user-images.githubusercontent.com/40891631/121208288-dc6e2e00-c871-11eb-8a62-43996c383dcb.png)

**Comment by corwintines** [comment]
@pettinarip do you think this is done? Saw it mentioned and looks like it would be in

**Comment by pettinarip** [comment]
@corwintines true. Yes, this is done. My bad for not closing it before. Closing it now. Thanks!
