### ISSUE TITLE
Cart info in tallying phase incorrect

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#104]
![image](https://user-images.githubusercontent.com/40891631/120463262-a32a4f80-c393-11eb-95e0-99c0533ca462.png)

I think the cart remembers the items you had in your cart when the reallocation phase ended, not how you actually contributed... 

After reallocation the cart should transition to your last contributed cart.

**Comment by samajammin** [comment]
Yes I believe this is a bug with how the cart relies on the /api/gun storage for a user's cart vs. querying the smart contract for what was actually committed to on chain.
