### ISSUE TITLE
Reallocation <> Matching pool error

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#105]
- If user contributes directly to matching pool, the number will update
- If user reallocates and some funds go to the matching pool, the matching pool total in the round info section doesn't update

This isn't actually possible to query matching pool contributions during reallocation (MACI holds these funds until tallying?)
- [x] @samajammin confirm this isn't possible to query
- [ ] @ryancreatescopy create some sweet copy (in the case we can't)

A) Add info to tooltip that explains reallocation contributions to matching pool won't show up right away? Or that not all matching pool amounts will be displayed until after the round is over?

`RoundInformation.vue`:

![Image 2021-06-02 at 9 16 46 AM](https://user-images.githubusercontent.com/8097623/120515629-56d71380-c383-11eb-820e-558106ce1cf1.jpg)

**Comment by samajammin** [comment]
Confirming this is not possible due to MACI.

@samajammin to create copy for this tooltip.
