### ISSUE TITLE
Cart indicator logic

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#112]
Should only pulse when you add something to the cart. At the moment it pulses on load (initial render) and on the first item added to cart but not when the cart quantity increases.

Standard:
![image](https://user-images.githubusercontent.com/40891631/120608558-38d3e680-c449-11eb-9f11-30442f6ba07d.png)

Pulse:
![Image 2021-06-08 at 9 40 37 AM](https://user-images.githubusercontent.com/8097623/121196182-1ebd4e00-c825-11eb-9b7e-1d0abaff7f6d.jpg)

When an item is added to cart, pulse animation should trigger. Look into action trigger as a way to toggle a class?

Question:
- should the cart indicator be persistent or should we hide it once you've looked at it like a notification? Decision for now: keep it persistent.

**Comment by pettinarip** [comment]
Right now, the indicator is pulsing only one time. 

1. User adds the first item or loads the page
2. The indicator pulse one time

I'm going to do the same when you add more items.
