### ISSUE TITLE
Contributor Leaderboard

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#114]
https://www.notion.so/efdn/Contributor-leaderboard-c091e4db30fb4fd08b4d5a0baee62d5f

Query contract for:
- contributor addresses + blockie/3box profile
- amount contributed, number of projects(?)
- order by contribution size

Link from contributors section in `RoundInformation.vue`

Early sketch:
![image](https://user-images.githubusercontent.com/40891631/120628467-a0dff800-c45c-11eb-8ee9-c2788bf155be.png)

Updated sketches;
![image](https://user-images.githubusercontent.com/40891631/120630417-bd7d2f80-c45e-11eb-8bcf-b96ff691e9aa.png)

As we're not supporting ENS right now, we can display the 0x address on top of the total amount. 

We may want to differentiate between matching pool contributors and regular contributors. Although this may be less important for us considering we expect most MP funds to come from the EF.

Have also mocked idea of showing allocation between projects and matching pool. But we could take this further and show % allocations between different projects. Need to confirm whether this leaks info we don't want...

![image](https://user-images.githubusercontent.com/40891631/120630940-38dee100-c45f-11eb-958f-480f068849ce.png)

**Comment by auryn-macmillan** [comment]
This is looking great!

@ryancreatescopy, you mentioned that we're not using ENS babes right now, how hard would it be to add that? Definitely a nice-to-have feature.

I'm not sure that the "all"/combined leaderboard makes sense. I'd probably just have the two separate leaderboards, one for direct contributions and one for contributions to the matching pool.

It might be out of scope for the ETH2 round, but it would also be really awesome to have a global leaderboard that factors in contributions to all rounds. Long term, another thing that might be nice to have is a profile for contributors that show a breakdown of their direct and matching pool contributions to each round.

**Comment by ryancreatescopy** [comment]
Thanks for the feedback!

![image](https://user-images.githubusercontent.com/40891631/120647217-418ce280-c472-11eb-98d9-5ac47ac3f82c.png)

Adding a quick dropdown so you can see leaderboards across rounds.

Like the idea of contributor profiles that show history, could also display POAPs for participation in each round etc. But yeah, out of scope for eth2 clr.

**Comment by samajammin** [comment]
Nice! Is the thought to show this at the Tallying phase? Or as soon as contribution phase is open?

Just to confirm - all this data is queryable? I will have to investigate this, or perhaps @auryn-macmillan can easily confirm. I think total amount contributed by each user is possible but I'm fairly certain a breakdown a user's contributions towards each project is not possible (I believe MACI obfuscates this): 
![Image 2021-06-07 at 11 10 22 PM](https://user-images.githubusercontent.com/8097623/121117222-a32fb280-c7cc-11eb-968e-e182a2d2b746.jpg)

**Comment by samajammin** [comment]
Note on fetching data - we know we can at least get aggregate data on total contributed per contributor address by tracking contribution events: https://github.com/ethereum/clrfund/blob/develop/contracts/contracts/FundingRound.sol#L51

**Comment by samajammin** [comment]
Note on where this should live - add a "more" button to RoundInformation component to view leaderboard:
![Image 2021-06-08 at 9 34 59 AM](https://user-images.githubusercontent.com/8097623/121194661-cdf92580-c823-11eb-99fc-ec7cfdf167ec.jpg)

**Comment by auryn-macmillan** [comment]
> I think total amount contributed by each user is possible but I'm fairly certain a breakdown a user's contributions towards each project is not possible (I believe MACI obfuscates this)

@samajammin, this is correct. We can't⁺, and don't want to, know how people allocated their funds. This is important for collusion resistance.

⁺ *the coordinator does actually have access to this information, but it should never be made publicly available. Long-term, we hope to build a coordinator that is incapable of sharing this information (or at least must collude with other coordinators to share the information).*

**Comment by samajammin** [comment]
Closing as abandoned.
