### ISSUE TITLE
QF helper demo

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#115]
https://www.notion.so/efdn/Quadratic-funding-demo-54169d045b844230a5f6bedc7aed3c24

A way to demo the power of QF based on real round matching pool data: https://www.figma.com/proto/gnA82CTLGjk0TfFHMvgyrK/CLR?kind=&node-id=833%3A1850&page-id=833%3A72&scaling=min-zoom&viewport=527%2C330%2C0.26004642248153687

![image](https://user-images.githubusercontent.com/40891631/120632580-0504bb00-c461-11eb-88d0-d710850b9841.png)
This screenshot shows what you'll see after adding a contribution to project 1. We highlight the other two projects and add an explainer of what has happened (e.g. matching amount has decreased)

The idea is that using the matching pool amount we can simulate how different donation amounts (and number of contributions) affect the overall distribution of the matching pool. 

We opted not to show estimated matching amounts when a user contributes for real as it leaks important data. This however is a way to still show the power of the tech while being general.

**Comment by samajammin** [comment]
Logic to define:
- How many donations can someone add on a project (e.g. limit to 5)?

Decisions to make:
- Where should this live? Help button that toggles a display on project list? Show on "how it works"? Create standalone page?

**Comment by samajammin** [comment]
A short term solution here may be to just link to https://wtfisqf.com/?grant=10&grant=5,5&grant=1,1,1,1,1,1,1,1,1,1&grant=&match=1000

It has a similar calculator.

**Comment by samajammin** [comment]
Closing as abandoned.
