### ISSUE TITLE
Total bar "down arrow"

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#116]
![image](https://user-images.githubusercontent.com/40891631/120640296-359d2280-c46a-11eb-87c7-1411d5716ebc.png)

The down arrow on the total bar should only appear when the cart extends beyond the view port. 
That means in the screenshot above, it shouldn't render.
It also means that when you get to the bottom and see the total bar pinned to the bottom of the screen you shouldn't see the downward arrow anymore...
I don't think it's necessary to have an upwards arrow in that case as all the actions are at the bottom of the cart

**Comment by samajammin** [comment]
Let's try removing the arrow - can decide during QA how difficult it is to discern that the cart is scrollable/that there's more action items below the fold.

@ryancreatescopy to explore potential alternatives (e.g. animation).

**Comment by samajammin** [comment]
@ryancreatescopy assigning to you to find/create a design you like for this. Don't feel the need to implement - please unassign yourself once you've attached design direction here 👍

**Comment by pettinarip** [comment]
@corwintines I was tracking where this button was removed and it is here #154. Correct me if I'm wrong, but should that PR close this issue as well?

**Comment by corwintines** [comment]
@pettinarip I believe so. Ill close.
