### ISSUE TITLE
Tallying cart bug

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#117]
If I have an item in my cart (that I don't actually include in a reallocation transaction) and the round transitions to tallying, it displays in my cart as if I contributed to it ! 

Tallying phase cart should only display projects that you actually contributed to NOT those that were in your cart at time of phase transition.

**Comment by samajammin** [comment]
I don't understand how this is any different than #104 - @ryancreatescopy could you please clarify?
