### ISSUE TITLE
Cart: implement "split evenly" for different round states

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#120]
![image](https://user-images.githubusercontent.com/40891631/121209074-72a25400-c872-11eb-8e33-688fca3575bd.png)

Based on whether the user is contributing or reallocating we should show different options in the dropdown menu in their cart.

If the user is contributing:
- remove all projects
- split "current connected wallet's" balance across projects

If the user is reallocating
- remove all projects
- split "original contribution total" across projects

In context:

![image](https://user-images.githubusercontent.com/40891631/121209368-b39a6880-c872-11eb-836f-050ccaa308fc.png)

This issue includes implementing the "split evenly" logic across contributions.

**Comment by samajammin** [comment]
Note on the split feature in the dropdown:
![image](https://user-images.githubusercontent.com/40891631/121208598-1808f800-c872-11eb-8888-e96c7a079eca.png)

We should disable this if the cart is already split evenly - so likely want to create a computed property to track this.

**Comment by samajammin** [comment]
@corwintines this is done, correct? Please re-open if that's not the case.
