### ISSUE TITLE
Profile/wallet z-index bug when opening from outside of Nav bar

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#122]
https://efdn.notion.site/Profile-wallet-z-index-bug-when-opening-from-outside-of-Nav-bar-62eafc2c977044d4a492d82efacfd7c3

![image](https://user-images.githubusercontent.com/54227730/121256668-a923a300-c861-11eb-9071-2bf7a93f829c.png)

When using `WalletWidget` without providing the prop `:isActionButton="true"` the full widget is utilized, which when clicked will toggle open the `Profile.vue` panel with incorrect z-index placement (renders _below_ the cart, when it should render above).

Expected behavior is demonstrated when using the WalletWidget located in the Nav bar, which will toggle the Profile.vue and keep it "on top" of the cart.

**Comment by corwintines** [comment]
Seems like we have refactored the bug away. Going to close for now.
