### ISSUE TITLE
Odd white padding around join transaction screen

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#123]
![image](https://user-images.githubusercontent.com/40891631/121316916-b1331f80-c901-11eb-85e9-9f1980054483.png)

browser: Brave

**Comment by ryancreatescopy** [comment]
Update: I believe this is the browser scroll UI on Brave. See examples on ethereum.org:

![image](https://user-images.githubusercontent.com/40891631/121359900-db013c00-c92b-11eb-83d2-628bfa0c84dc.png)

Might be my new monitor (wide screen) as I wasn't seeing these before. Either way it's not ideal, what can we do?

**Comment by samajammin** [comment]
Hmmm ya the page should be scrollable, not the element/container within this page.
