### ISSUE TITLE
IPFS hash wrapping bug

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#124]
![image](https://user-images.githubusercontent.com/40891631/121316726-847f0800-c901-11eb-8184-0607550233fe.png)

Why does this wrap when there's enough space to display entire hash? Perhaps we're setting an arbitrary width but I feel like it should not have wrapped in this instance

**Comment by samajammin** [comment]
Agreed re: this situation/screenshot. Curious to hear your take @ryancreatescopy what should the behavior be when there's not enough space, e.g. on mobile? Should the hash wrap? Should we add horizontal scroll? Should we truncate?

**Comment by ryancreatescopy** [comment]
I think it's fine to truncate this as I doubt users will be checking entire strings. They have the option to copy whole hash or view via IPFS
