### ISSUE TITLE
Landing page layout bug after JoinPhase

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#125]
When the join phase is over, the invitiation to joint he round on the landing page disappears leaving us with a weirdly sized landing area. We should still display the entire image and not shrink the size.

When Join is open:
![image](https://user-images.githubusercontent.com/40891631/121316156-f014a580-c900-11eb-8ba2-8d9837f3a601.png)

When Join is closed:
![image](https://user-images.githubusercontent.com/40891631/121317387-27d01d00-c902-11eb-9871-9156d1fdaaea.png)

**Comment by corwintines** [comment]
Merged in above PR.
