### ISSUE TITLE
Cart project contribution total shouldn't wrap

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#127]
![image](https://user-images.githubusercontent.com/40891631/121322313-c52d5000-c906-11eb-9850-8a80c1055422.png)

Like the above screenshot we should try and avoid the totals wrapping as this will make them harder to read, it would always be preferable to wrap the project name rather than the totals. Ideally you'd want all totals to line up right-aligned in the cart so it's easy to do quick math

**Comment by corwintines** [comment]
Merged in above PR.
