### ISSUE TITLE
Contributor key not found error modal

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#129]
https://efdn.notion.site/Contributor-key-not-found-error-modal-c1863fd7cfe4493a9c0bf223bb345e9d

There's an edge case where the gunDB may not be able to find your contributor key. This will prevent you from reallocating. We should check on connection whether the contributor key is found or not, and if not display an error message with some help. At the moment, this error is displayed in the cart, which could be annoying for a user if they've invested time in configuring a reallocation in their cart.

Advice needed to include in the modal:

```
**Sorry, something's wrong...**

Your project contributions are safe but we've found an error that will prevent you from editing your choices. Make sure you're using the same browser/machine as the one you contributed with, then refresh and try again. It's likely an error with our decentralized database that stores information needed for you to change your choices.

[OK]
```

Ok should close the modal. 

---

We may also want to transition this user to the tallying state. So we show that the round is closed and display a read-only version of their cart that shows how they contributed. While the user is seeing this error they are effectively in a post-round state because there's nothing they can do (except add to matching pool)

**Comment by samajammin** [comment]
Closing this out - please move discussion to https://github.com/ethereum/clrfund/issues/129
