### ISSUE TITLE
currentRound.contributors >= currentRound.maxContributors

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#130]
Ideal:
- MACI removes maxContributors

Fallback:
- transition contribution phase to reallocation phase for everyone

Fallback fallback:
- Remove 'get prepared' card (replace with "round over" card) for users who haven't contributed
- Remove "add to cart" from project cards for users who haven't contributed
- Remove "add to cart" from project page for users who haven't contributed
- Display "round closed" in "round information" for users who haven't contributed
    - Should we address this in the MACI article and link to this?
- Display funding closed roundbanner (landing page)
    - *Funding is closed! If you contributed, you have {{reallocationTimeRemaining}} left to change your mind*
- For users who have contributed, use all content that's conditional on `userCanReallocate`

**Comment by samajammin** [comment]
So we should add these checks in the `isRoundContributionPhase` & `isRoundReallocationPhase` store getters.

**Comment by samajammin** [comment]
Currently we at least display the issue:
![Image 2021-08-05 at 1 31 57 PM](https://user-images.githubusercontent.com/8097623/128417165-09387224-9c0a-48ed-b78f-a7542bdfe045.jpg)

**Comment by samajammin** [comment]
I think that might actually be enough - it might create confusion e.g. if we say the round is open for contributions until a certain date but then we display the round as over before then.

**Comment by samajammin** [comment]
Also the increase in MACI capacity (https://github.com/ethereum/clrfund/pull/221) makes this less of a concern...

I'm going to close this out for now. Feel free to re-open if you want to weigh in!

**Comment by pettinarip** [comment]
> I think that might actually be enough - it might create confusion e.g. if we say the round is open for contributions until a certain date but then we display the round as over before then.

Agreed. It would be confusing to see that the round is closed before the end date. I prefer the current approach.
