### ISSUE TITLE
currentRound.messages >= currentRound.maxMessages

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#131]
Ideal:
MACI removes maxContributors

Fallback:
transition contribution/reallocation phase to tallying phase for everyone

Fallback fallback:
- For `userCanReallocate` users, remove 'you can reallocate' card (replace with "round over" card)
- Remove "add to cart" from project cards for `userCanReallocate` users
- Remove "add to cart" from project page for `userCanReallocate` users
- Display "round tallying" in round information (landing page)
- Display tallying round banner
    - *Funding is closed! Our smart contracts are busy tallying contributions...*

**Comment by samajammin** [comment]
Same deal as #130 here. We at least display the constraint in the UI:

![Image 2021-08-05 at 1 39 25 PM](https://user-images.githubusercontent.com/8097623/128418052-d30d3cab-31a6-4665-9dc0-68aceccaa72c.jpg)

The increase in MACI capacity (#221) makes this less of a concern...

I'm going to close this out for now. Feel free to re-open if you want to weigh in!
