### ISSUE TITLE
Time left tooltip

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#133]
Due to #130 and #131,  when we display "time left" we should caveat it in some way that phases are subject to close earlier than we advertise.

I propose we add a tooltip wherever we display time left and say something like:

```
The funding round has certain limits so, if it's busier than expected, the time left may actually be less. Don't wait until the last minute to avoid disappointment. 
```

I'm hoping something like this won't be too confusing and covers us against unexpected round transition. Feel free to oppose this, my confidence in this feature isn't high. 

In this tooltip we can link to the constraints section of the MACI article:
![image](https://user-images.githubusercontent.com/40891631/121342063-31b14a80-c919-11eb-88a3-c166c5c73901.png)

**Comment by samajammin** [comment]
Given the expanded MACI caps, I think explaining this on the MACI page is enough.
