### ISSUE TITLE
Enforce max size of hero images

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#14]
https://www.notion.so/efdn/Enforce-max-size-of-hero-images-cb19513a944f4484ae282407e80d5fb6

For most screen sizes the hero images look great but for smaller & XL desktop screens they look a bit crazy. I suggest we limit the size so the image is never spilling outside the viewport.

e.g.

![Image 2021-04-23 at 11 39 11 AM](https://user-images.githubusercontent.com/8097623/115915839-c7a41b00-a428-11eb-946b-912678dd7a72.jpg)

![Image 2021-04-23 at 11 40 07 AM](https://user-images.githubusercontent.com/8097623/115915851-cb37a200-a428-11eb-9e62-475ed689d572.jpg)

**Comment by ryancreatescopy** [comment]
Is this fixed @samajammin @wackerow ?

**Comment by samajammin** [comment]
I don't believe so. @ryancreatescopy do you have a sense of what the max width/height of these images should be?
