### ISSUE TITLE
Investigation needed: joinPhase

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#141]
While I was playing with the product today, I started the process of Joining and got to the transaction page. I went off to make a coffee etc, came back and although the contribution and reallocation phase was over, I was still able to submit the transaction and I got the "Project submitted" success page.

If a user delays submitting the tx and the join phase ends, we should stop them from being able to transact. Instead we should have an error that states that the join phase is over. This could result in a lot of frustrated users, wasted gas fees etc..

Unsure whether this is due to the fact that our local doesn't really have a join phase. So investigation is needed to make sure this isn't behaviour that will leak over into the proper round!

**Comment by samajammin** [comment]
This has been fixed.
