### ISSUE TITLE
Display estimated tx fees

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#151]
https://www.notion.so/efdn/Display-estimated-transaction-fees-0abd2617045645eca1acc8d678855af7

Related to e.g. #67 in the RecipientSubmissionWidget component:

![image](https://user-images.githubusercontent.com/8097623/122076958-2befb500-cdb0-11eb-9ac2-c44f7dce754d.png)

Some context on approach using ethers.js: https://ethereum.stackexchange.com/questions/100209/estimate-gas-price-with-ethers-js/100210

1. query estimated current gas price (https://docs.ethers.io/v5/api/providers/provider/#Provider-getGasPrice)
2. querying the gas required (https://docs.ethers.io/v5/api/providers/provider/#Provider-estimateGas)

We could optionally display a fiat estimate of the tx fee as well:
3. query the price of ETH (e.g. https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd)
4. calculate price of ETH * current gas price * gas required

**Comment by corwintines** [comment]
Just to note on this, some changes to what is in there (marked by TODO comments) will have to come when either:
1 - EIP-1559 gets merged in
2 - To work with whatever layer 2 we use (Arbitrum)

**Comment by samajammin** [comment]
Closing this as abandoned.
