### ISSUE TITLE
Displaying wrong total after Contribution Phase

### ISSUE THREAD

**Issue by corwintines** [ethereum/clrfund#152]
Currently the cart total for the contribution phase is correct, it is summing up the cart, and displaying the total. 

Reallocation phase onwards it is showing the wrong total though. Currently, it is summing up the committedCart item amounts. This works fine unless there is a reallocation that takes place where there is not a full reallocation and some goes to the cart. Ex:
- User contributed 100 DAI, 50 DAI to 2 projects in contribution phase
- Total shows 100 DAI because that is the committedCart sum. This is correct here. 
- User Reallocates funds. 45 DAI to 2 projects, and submits the reallocation. This would mean there is 10 DAI going to matching pool
- Total shows 90 DAI now, when it should still show 100 DAI

To fix this, need to return in the getTotal function currentRound.contribution in Cart.vue. This will show the total contribution which will include all cases of reallocation where the full amount wasnt reallocated to projects and has a matching pool amount.

**Comment by samajammin** [comment]
Related to this (I think the same issue) - I noticed the cart amount wasn't adding up correctly during reallocation:

![Image 2021-06-17 at 2 28 43 PM](https://user-images.githubusercontent.com/8097623/122474827-981d1500-cf78-11eb-8aa8-cd29c05e5a17.jpg)

Scenario
- I contributed 15 DAI to 2 projects
- I edit cart during reallocation: 1 project to 10 DAI
- "Your cart" line item still displays 30 DAI (should be 25 & an additional "Matching pool" line item of 5)
- In this case, the total should still display 30 DAI

**Comment by samajammin** [comment]
https://user-images.githubusercontent.com/8097623/122656598-e9600c80-d110-11eb-94a0-68a1d504a9e3.mp4
