### ISSUE TITLE
Can't dismiss "connect your wallet" modal

### ISSUE THREAD

**Issue by auryn-macmillan** [ethereum/clrfund#161]
![image](https://user-images.githubusercontent.com/8453294/122809624-581da100-d29c-11eb-992a-450bd4ac5097.png)
There is no way to close this modal, triggered by clicking the kebab icon next to "contributors" when you are not logged in.

**Comment by auryn-macmillan** [comment]
Also worth noting that this modal doesn't darken the rest of the app nor contrast well. So it's not immediately obvious that its even there.

**Comment by ryancreatescopy** [comment]
+1 you get stuck if you're unconnected and not using a wallet-supporting browser. Praying for WalletConnect 🙏 :) 

![image](https://user-images.githubusercontent.com/40891631/123254761-f2712500-d4e6-11eb-9ec3-bb0476256e11.png)

**Comment by samajammin** [comment]
Agreed, I think the best solution here is WalletConnect, which @corwintines will be looking into this sprint 🏃
