### ISSUE TITLE
Big number in contribution button

### ISSUE THREAD

**Issue by pettinarip** [ethereum/clrfund#163]
**How to reproduce?**
1. Add a project to the cart.
2. Enter a big number in the contribution input.
3. Check how the content of the contribution button exceeds the button space.

![big numbers](https://user-images.githubusercontent.com/468158/122832184-5ac8d680-d32e-11eb-845a-7e3a47bdc9e6.png)

**Comment by wackerow** [comment]
So within `FundingRound.sol` we set a max contribution amount...
```sol
uint256 private constant MAX_CONTRIBUTION_AMOUNT = 10 ** 4;  // In tokens
```
...placing a cap of 10,000 on the contribution amount. @corwintines I forget what we decided before... how many decimals were we going to allow? I think 5 would be plenty, and would simplify the above issue as the number should never be more than 9 digits that way.

(Should also double check to make sure that parameter won't change dramatically.)

**Comment by corwintines** [comment]
@wackerow I think it was 5 decimal points that was there.

**Comment by pettinarip** [comment]
To clarify, the validation rules are being applied to the input value (such as the maximum contribution amount). You can see one of the error messages in the screenshot, above the Contribute button.

The problem here is style related as the form allows you to enter any contribution amount in the input and makes the button's content not fit into the space it has.

Possible solutions I can think of:
1. Set a maximum number in the input so that the user cannot type any number greater than MAX_CONTRIBUTION_AMOUNT.
2. Add an ellipsis (...) to the number.
3. Remove the contribution number from the button.

I like the 1 one.

**Comment by wackerow** [comment]
Agree, I like 1. Implementing now in PR #194
