### ISSUE TITLE
Add transaction states to Recipient flow

### ISSUE THREAD

**Issue by corwintines** [ethereum/clrfund#168]
After releasing on the test net, check/implement the following for completeness

- [ ] Confirm tx pending state displays as expected. At the moment it redirects you straight to the success page. I believe this is due to the fact that Hardhat mines all txs immediately by default. We should test this out with a mining interval added. See Upgrade Hardhat version clrfund/monorepo#355 for how this can be accomplished.
- [ ] Add/confirm logic for isLoading, isWaiting, isWrongNetwork, isTxRejected, txError

**Comment by samajammin** [comment]
Can confirm we need to fix/add the `isPending` state for pending txs. See this example: https://share.getcloudapp.com/4gunZDeb

The RecipientSubmissionWidget displayed "Check your wallet for a prompt..." the whole time the tx was pending. It should display the waiting message until the user clicks "confirm" to send the tx. Once they've submitted the tx, we should display something like "Submitted your transaction to the network. Pending confirmation..."

**Comment by samajammin** [comment]
This has been fixed, confirmed in recent Rinkeby tests.

**Comment by samajammin** [comment]
Ac
