### ISSUE TITLE
Only validate email/address fields on blur

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#17]
Making a note on this to make it easier to keep track of.

We shouldn't validate the contact email or Ethereum address field immediately... 

e.g. 
![image](https://user-images.githubusercontent.com/40891631/116221327-6db39600-a745-11eb-817c-573bd27ff351.png)

**Comment by samajammin** [comment]
We investigated this & couldn't find a quick fix using vuelidate. Marking as low priority.

**Comment by pettinarip** [comment]
Found it here: https://vuelidate-next.netlify.app/guide.html#using-touch
