### ISSUE TITLE
AddToCartButton disabled when it shouldn't be

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#170]
Appears to be an issue with `hasContributeBtn` - is this needed (since we now have `canContribute`)?

![Image 2021-06-23 at 6 54 46 PM](https://user-images.githubusercontent.com/8097623/123191580-5992c900-d456-11eb-8240-8e8f6f763f13.jpg)

**Comment by samajammin** [comment]
Actually, this may be working somewhat as intended.

These 2 projects ([on our testnet](https://eth2clrfund.netlify.app/#/projects)) have a request in the registry but those request have not actually been executed, therefore their `index` is `0`:
https://github.com/ethereum/clrfund/blob/develop/vue-app/src/api/recipient-registry-optimistic.ts#L312

That disables the button (because `hasContributeBtn` is false:
https://github.com/ethereum/clrfund/blob/develop/vue-app/src/components/AddToCartButton.vue#L80

In this case, we should either
A) hide the project entirely from the project list (since EF will be executing the recipient registry requests)
B) hide the "add to cart" button on the project card
C) make it more obvious that the button is disabled

**Comment by corwintines** [comment]
@samajammin @pettinarip @wackerow Going to opt for option b here and see what you guys think. I think option A will be handled from https://github.com/ethereum/clrfund/pull/174, and if we just hide it them option  C will be handled

**Comment by samajammin** [comment]
Thanks @corwintines but since we've already solved A) is B) needed at all?

**Comment by samajammin** [comment]
(I suppose it wouldn't hurt but it doesn't seem necessary)

**Comment by corwintines** [comment]
@samajammin probably isnt necessary, I just added it in incase since it was very small addition of a conditional. If we don't want to merge it my feelings won't be hurt.
