### ISSUE TITLE
Todo shows on load

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#173]
<img width="326" alt="Screenshot 2021-06-24 at 12 45 44" src="https://user-images.githubusercontent.com/40891631/123257510-2dc12300-d4ea-11eb-8933-47527ef82f7c.png">

When the round info is loading, this line of copy appears and then disappears.

**Comment by corwintines** [comment]
Closing since https://github.com/ethereum/clrfund/pull/179 was merged
