### ISSUE TITLE
Increase margin on form flows (join & brightId)

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#18]
https://www.notion.so/efdn/Increase-margin-on-form-flows-de7da1e9a75b4db8911a8767472d6f4c

As per designs, I think it's nicer if we have more left and right margin so that the form and progress module sit more centrally in the page...

In dev:
![image](https://user-images.githubusercontent.com/40891631/116221552-a2275200-a745-11eb-8964-44fe11fd5022.png)

In design:
![image](https://user-images.githubusercontent.com/40891631/116221687-bff4b700-a745-11eb-94ef-85c448343d33.png)

Happy to debate this, not something I'm precious about but just wanted to make sure we had the conversation...

**Comment by ryancreatescopy** [comment]
@samajammin @wackerow thoughts on this?

**Comment by samajammin** [comment]
Yes let's do this 👍
