### ISSUE TITLE
When you clear an image it doesn't remove filename

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#20]
https://www.notion.so/efdn/When-you-clear-an-image-it-doesn-t-remove-filename-d199454f269a485e8aed5df60595cc91

When you "clear" an image it doesn't remove the filename from the input. It then appears as if you have an image selected but "Upload" is disabled. Ideally, "clear' should empty the file input. 

![image](https://user-images.githubusercontent.com/40891631/116223331-5675a800-a747-11eb-8388-f7e81bcfa178.png)

**Comment by samajammin** [comment]
This may not be possible but let's please confirm.
