### ISSUE TITLE
Recipient cannot view own project immediately after submitting

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#202]
After a user applied as a recipient, there is no way for the user to view that their project exists in the UI. 

_Ref post by @pettinarip in https://github.com/ethereum/clrfund/issues/193#issuecomment-875825933_

Should we consider a way for these to be viewed before approval? Should edits be allowed?

**Comment by wackerow** [comment]
Discussion in #170 relates as well

This may be something more appropriate for a later iteration of the app.

**Comment by samajammin** [comment]
Ya I don't think is needed. Closing this out - feel free to re-open if you'd like to advocate for this feature.
