### ISSUE TITLE
Finalized State bugs

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#205]
https://www.notion.so/efdn/Finalized-State-bugs-afc0b8315b6d4007843df884fddf40a9

![image](https://user-images.githubusercontent.com/54227730/125870150-614240a0-29ee-4d8a-bff8-6afa2794bc5d.png)

Notable issues within this screenshot:
- [ ] "Open" indicator should be "Closed".
- [ ] Endless spinner on bottom left
- [ ] "⊕ Add funds" and "•••" indicator both open modal to "Contribute to next round"... wanted to double check this is what we want when the Eth2 round finalizes
- [ ] "Contributions are ready to claim" yet there is no button to claim for eligible recipient

**Comment by samajammin** [comment]
> "Open" indicator should be "Closed".

Note: this should also show "Closed" if round is Tallying.

**Comment by samajammin** [comment]
> "⊕ Add funds" and "•••" indicator both open modal to "Contribute to next round"... wanted to double check this is what we want when the Eth2 round finalizes

Good point - I think we should remove these actions if the round is finalized, given we likely won't actually run another round on these specific contracts....

**Comment by samajammin** [comment]
>  "Contributions are ready to claim" yet there is no button to claim for eligible recipient

@wackerow are you sure this is still an issue? I suppose we'll see with this recent test round 😄

**Comment by wackerow** [comment]
@samajammin No, I am not sure, was planning on testing again w/ this past test round. Could try to find some time to do a test of this locally since the last test round couldn't be finalized.
