### ISSUE TITLE
Specify which network to connect to in the wallet modal

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#231]
https://www.notion.so/efdn/Specify-which-network-to-connect-to-in-the-wallet-modal-a4806dfd4bec4e8cbf4723944ba84d7d

1. I'm logged into MetaMask on Mainnet
2. I go to https://eth2clrfund.netlify.app/#/projects
3. I click "Connect"
4. I click MetaMask option
5. I sign the Signature Request modal
6. I see this error:
![Image 2021-08-05 at 12 05 36 PM](https://user-images.githubusercontent.com/8097623/128408192-7e098610-4743-48ad-9625-8646227249ec.jpg)

A few things we could improve:
- [ ] Update the error copy to specify which network to connect to, i.e. "Wrong Network. Please connect to the appropriate Ethereum network." --> "Wrong Network. Please connect to the [network_name] Ethereum network."
- [ ] If we can already detect a provider before step 4 (i.e. before they make a selection), we should display that warning so the user avoids having to go through step 4 & 5.

**Comment by samajammin** [comment]
More feedback on this:
> If you are on the wrong network, the error message is uninformative about which network to switch to. Ideally, the app should trigger metamask to add and switch to the correct network.

**Comment by pettinarip** [comment]
Aha! okok, so we should by default check if there is a something in window.ethereum (aka metamask). Assuming the user is going to connect with that. And proactively we show that the user is in the correct or incorrect network, as we were doing before I think.
