### ISSUE TITLE
Tooltip z-index issue

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#235]
https://www.notion.so/efdn/Tooltip-z-index-issue-dd87a35f318b4bf99209a80a4f25fc73

Displays behind project cards:
![Image 2021-08-05 at 1 13 52 PM](https://user-images.githubusercontent.com/8097623/128414990-d478fd80-a263-4255-985b-5dfb0bf84d60.jpg)

**Comment by Patil2099** [comment]
I would love to take this up
