### ISSUE TITLE
Potentially confusing location of "Submit" button for new receipients

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#240]
![image](https://user-images.githubusercontent.com/54227730/128442582-a2ce8f2a-2f9f-4274-8b4d-a345fadefe06.png)

Was suggested through user feedback that after the entire `Join` form flow has the "continue" button in the same place, but the final step to submit moves the button to the middle. 

Filing here for discussion.

**Comment by pettinarip** [comment]
Closing since we have moved this issue to the monorepo: https://github.com/clrfund/monorepo/issues/445
