### ISSUE TITLE
Figure out rendering IPFS images uploaded with ipfs-mini

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#25]
I suspect something is off with the way we're uploading it

Currently fetching the IPFS hash of an image we've uploaded, e.g.
https://ipfs.io/ipfs/QmP4qZzXSZpC7sHmsKwYfxZVAzp9tZiDGEpNKzUwA4YzEt

Yields the data, not the image.

**Potential solutions** 
- https://github.com/SilentCicero/ipfs-mini/issues/4 (which uses `add` vs. our `addJSON` approach
- https://bountify.co/upload-an-image-to-ipfs-using-ipfs-mini

**Comment by ryancreatescopy** [comment]
is this fixed @samajammin @wackerow ?

**Comment by samajammin** [comment]
@wackerow please confirm if this has been fixed (I feel like you did fix this).
