### ISSUE TITLE
Extract inline styling to CSS classes

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#261]
There are many stray uses of inline styling left over from initial templating. We should clean these up and extract them into CSS classes. The most notable file would be `RoundInformation.vue` but there are others that would benefit:

![image](https://user-images.githubusercontent.com/54227730/129278136-0290efe0-a9ed-4125-9b90-329284a17078.png)

**Comment by samajammin** [comment]
💯

**Comment by wackerow** [comment]
The `RoundInformation` instances were cleaned up with commit b1078bc14753680175e752eb36e42a0413c71a1f. Will address the others in a separate PR before closing this.
