### ISSUE TITLE
Hide MetaMask as option on mobile?

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#269]
Should we hide MetaMask as an option on mobile?

![clr fund - clr fund 2021-08-17 at 3 09 58 PM](https://user-images.githubusercontent.com/8097623/129807422-aac6f145-a134-4c51-9b16-c71372fb207d.jpg)

Perhaps pop them straight into WalletConnect?

![clr fund - clr fund 2021-08-17 at 3 10 12 PM](https://user-images.githubusercontent.com/8097623/129807438-786cee7b-2fa4-4a37-a9d5-215e19f51761.jpg)

Curious what other apps do / what best practices are here 🤔

**Comment by corwintines** [comment]
@samajammin if they are using metamask on mobile would we just assume connecting to metamask?
I know when I use these dapps in metamask, the apps seem to assume im going to connect with metamask and just connect that. Maybe we check if they are connecting through metamask or another browser, and handle that accordingly when on mobile?

**Comment by wackerow** [comment]
Yeah, agree that the subset of people who load this directly from MetaMask browser would not need the WalletConnect option, even though they are on mobile.

**Comment by samajammin** [comment]
> @samajammin if they are using metamask on mobile would we just assume connecting to metamask?

Ah, I suppose I just assumed you couldn't use MetaMask on mobile (since it's a browser extension). Seems that's not the case?

**Comment by samajammin** [comment]
Just confirmed, I can use MetaMask via MetaMask mobile app & the in-app browser. Gonna close this out.
