### ISSUE TITLE
Keyboard accessibility

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#274]
Noticed inability to connect a wallet using the keyboard.

If user tabs to the "Connect" button, they can open the modal to chose a wallet, but cannot tab to the wallet options, nor the close button. ESC key doesn't help here.

![image](https://user-images.githubusercontent.com/54227730/129974361-5179c068-f13f-4ecc-9856-167803af3336.png)

Also seems to affect the NavBar which has no tab stops for the ﹖ menu or the home icon.

**Comment by samajammin** [comment]
Agreed! Just found myself trying to hit ESC to exit the modal 😄
