### ISSUE TITLE
Add opacity to TransactionSuccess

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#276]
The text is a bit hard to read on this page:

https://user-images.githubusercontent.com/8097623/129980482-0f7ed03f-93c4-4585-a5db-d0d2cf728663.mp4

e.g. https://eth2clrfund.netlify.app/#/transaction-success/contribution/0x46a770d89b84d4dc6a62b0f9c6c567509459f6a10b44956500ce6ed83698a5fd

Should we add a layer of opacity so it's easier to read?
Alternatively we could adjust the image so it doesn't overlap with the test (like on the homepage: https://eth2clrfund.netlify.app/#/).

**Comment by Patil2099** [comment]
I would love to take this up.

**Comment by pettinarip** [comment]
Fixed in #304
