### ISSUE TITLE
"Disabled" button styling buggy with redundant css

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#278]
Several components/views implement their own `.disabled` class, which are all pretty much the same.
ie:
- components/Cart.vue
- components/FormNavigation.vue
- components/IpfsImageUpload.vue
- views/Join.vue
- views/Verify.vue 

Some places require some cleanup to get the buttons to display "disabled" correctly.

Suggesting we extract and consolidate these into the `_theme.scss` file as a `disabled` boolean attribute on any of our styled buttons, instead of a class.

Will submit a PR for this after #262 gets merged

**Comment by samajammin** [comment]
@wackerow agreed - thanks for submitting. Please add that `cursor: not-allowed` so it makes it obvious the button is disabled.
