### ISSUE TITLE
Mobile - Recipient Registration form flow

### ISSUE THREAD

**Issue by corwintines** [ethereum/clrfund#299]
To do
- [ ] "Next" button should be on the right at all times
- [x] Scrolling to bottom should not lift nav bar
- [x] ProgressBar should be sticky to top
- [x] Edge case: long string bring placed in markdown field will render off screen
- [x] Placeholder for URLS changed from example to ex
- [x] Full width buttons in Upload
- [x] Funding address layout improvement
- [ ] address shortened for mobile when transaction submitted

**Comment by samajammin** [comment]
In addition to the styling here please investigate the logic - I'm not sure if we implemented a separate component or what for the mobile navigation. I _believe_ we do share logic across the FormNavigation component but I'm not positive.
