### ISSUE TITLE
Mobile - BrightID ready to contribute page

### ISSUE THREAD

**Issue by corwintines** [ethereum/clrfund#302]
'Go Home' button in ready to contribute page for BrightID flow is hard to read.
<img width="222" alt="Screen Shot 2021-08-25 at 4 47 48 PM" src="https://user-images.githubusercontent.com/15589226/130878999-ec1765a8-8b10-4247-b421-281f3482d8da.png">

**Comment by samajammin** [comment]
Related - the styling of that Etherscan button looks off (for both desktop & mobile). Let's:
- vertically align the icon & text of the button
- get rid of the arrow (or move it to be within the button)

**Comment by samajammin** [comment]
FYI I created #310 which relates to your comment on populating the transaction.

**Comment by corwintines** [comment]
Thanks @samajammin, will take transaction part out of this

**Comment by corwintines** [comment]
@samajammin im thinking this btn-secondary class might be worth looking into a decent background color to fix this. Have noticed this in a few places around the app, and its somewhat a consistent issue. Will try and come up with a decent design and see what we think.

**Comment by corwintines** [comment]
Going to close as the button issue would be broader, and the rest of these issues have been addressed in other PR's
