### ISSUE TITLE
Confirm active round just before recipient join form submission

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#309]
https://www.notion.so/efdn/Confirm-active-round-just-before-recipient-join-form-submission-9ec3f6a78cda462a95366a3ecdc83e6d

🐞 If the recipient Join form is started while the round is still active, but completed *after* the round ends, the user is currently allowed to submit their project request. If they return to the Join Landing screen we block them from signing up.

🔨 We should do a final check on the submission step to make sure applications are still being accepted, and block sending a transaction if the round has since expired.

**Comment by samajammin** [comment]
Agreed, good catch!
