### ISSUE TITLE
TypeError: Cannot read property 'isVerified' of undefined

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#320]
Saw this error when opening my profile. My guess is we're not doing a proper check if we haven't yet fetched the user/BrightID data.

![clr fund - clr fund 2021-08-29 at 2 17 02 PM](https://user-images.githubusercontent.com/8097623/131265633-4868c8f2-68e8-4bed-ac75-71f067ebbf07.jpg)

To reproduce:
1. Connected my wallet
2. Navigated to https://eth2clrfund.netlify.app/#/projects
3. Opened my profile
4. Saw console error

**Comment by corwintines** [comment]
@samajammin im having issues reproducing this now. Not sure if something went through to fix this already.
