### ISSUE TITLE
Truncate native token balance in WalletWidget

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#327]
Looks a bit unwieldy, particularly on mobile:
![clr fund - clr fund 2021-08-30 at 4 35 14 PM](https://user-images.githubusercontent.com/8097623/131419046-1f08675c-014d-4107-9d06-0d490ae35203.jpg)

![clr fund - clr fund 2021-08-30 at 4 34 47 PM](https://user-images.githubusercontent.com/8097623/131419054-d8a7935a-5d56-4c2e-b50b-dac6b283d640.jpg)

Should we truncate this down, e.g. by rounding to 2 or 3 decimal places?

**Comment by samajammin** [comment]
Related tho this, the Profile component now takes up more than full width:

https://user-images.githubusercontent.com/8097623/131419229-c330487d-f67a-4696-9d79-373082054864.mp4

I bet we could adjust the spacing to make this all fit?

**Comment by samajammin** [comment]
Hold up - this might just a regression in #314

**Comment by wackerow** [comment]
Made a comment on that PR... this looks like a separate issue relating to not rounding decimals to 5 places like we're doing in other components. Assigning myself.

**Comment by wackerow** [comment]
@samajammin While on this topic though, perhaps we should consider hiding the wallet address in the WalletWidget entirely on mobile screens. I played around with this and it looked good, and provides much more leeway for larger DAI balances (like, all the DAI):

![image](https://user-images.githubusercontent.com/54227730/131432692-95635b71-ff8d-4b5d-a0e4-0d044b54f952.png)
