### ISSUE TITLE
Timeout in BrightID sponsorship

### ISSUE THREAD

**Issue by corwintines** [ethereum/clrfund#342]
Often users are being timed out during sponsorship for BrightID and they need to disconnect and reconnect to get their current state. To improve the user experience, we should add some text explaining what is going on, or a button to check status. Open to ideas here.

**Comment by pettinarip** [comment]
Is the sponsorship tx the one that is timing out?

Isn't this related to the work done here? #417

**Comment by corwintines** [comment]
I think this is related now yeah, ill tie this in too.
