### ISSUE TITLE
BrightId success page  tx receipt maligned at specific widths

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#352]
https://www.notion.so/efdn/BrightId-success-tx-receipt-malignment-60786ae660de4ed1a49b389820fb3e2c
Screen widths from 721-800 were causing this layout with the Tx Rceipt next to the header

<img width="735" alt="Screen Shot 2021-09-02 at 15 42 27" src="https://user-images.githubusercontent.com/54227730/132364200-5973cfc3-2d0b-4a84-99a8-35f054bd8c1d.png">

Should wrap under the header as it does with other screen widths.

**Comment by samajammin** [comment]
Agreed, tx receipt should wrap.

We should also add spacing between buttons if that's not already been fixed.

**Comment by samajammin** [comment]
Confirming that buttons have spacing but the tx receipt doesn't wrap at a certain width:
https://eth2clrfund.netlify.app/#/verify/success/0x1cc5300bd6e51731d11d2699901b64014e04a11126af3de4123835018f4b6045
![clr fund - clr fund 2021-09-21 at 7 22 12 AM](https://user-images.githubusercontent.com/8097623/134188704-95d009f5-9615-4009-9d36-d6446a7efbf8.jpg)
