### ISSUE TITLE
BrightId get registered step bugs

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#353]
https://www.notion.so/efdn/BrightId-get-registered-bugs-9e93fac3fdf94832958442abdbe01f5a
<img width="760" alt="Screen Shot 2021-09-02 at 15 36 44" src="https://user-images.githubusercontent.com/54227730/132364637-73a39eee-564c-439f-b9ea-c11fc537bd04.png">

- [ ] Update button styles - doesn't need to be full width on desktop
- [ ] Add spacing under button
- [ ] use "registry" instead of "register"
- [ ] use the tx receipt component here instead?

**Comment by samajammin** [comment]
> Do we want this to be a full width button even when not on mobile?

No I don't think we should - are there tx flows elsewhere we can copy, like the join flow?

> This button needs some spacing under it

Agreed.

> Small note, should we use "registry" instead of "register"?

Yes!

> Should we use the tx receipt component here instead?

Yes!

**Comment by samajammin** [comment]
@wackerow updated the issue description to reflect the TODOs here.

**Comment by samajammin** [comment]
For reference this is how the join tx looks:
![clr fund - clr fund 2021-09-21 at 7 42 36 AM](https://user-images.githubusercontent.com/8097623/134192411-900720d4-f96d-4caa-a0be-53ffa6a87c53.jpg)
Not sure how much it makes sense to mimic this 🤔 - open to ideas on how to lay this out.

**Comment by corwintines** [comment]
Ill follow this as close as I can, but not enough information to fill out this widget as well.
