### ISSUE TITLE
BrightId card displayed while fetching the BrightId endpoint

### ISSUE THREAD

**Issue by pettinarip** [ethereum/clrfund#394]
**How to reproduce (watch the video):**
1. Load the app without connecting the wallet
2. Once everything is loaded, connect your wallet with a BrightId verified and registered user
3. Check that for one or two seconds the BrightId is shown and then hidden

https://user-images.githubusercontent.com/468158/134969278-f24d1439-e4af-4551-b28f-dbcdb884bfe4.mp4

**Expected:**
While we are fetching the BrightId state from its endpoint we should not show the BrightId card.

**Comment by corwintines** [comment]
Closing with merged PR
