### ISSUE TITLE
App not switching to reallocation phase after contribution

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#403]
Steps I took:
1. https://eth2clrfund.netlify.app/#/projects (Pointing to 0xCfcA479E6DD9470Bb1eDaf046Daced25f4627948 Rinkeby Arbitrum at time of filing)
1. Connected, Verified BrightID
1. Added one project, contributed 100 DAI, ended up on success page
1. Attempted to reallocate and was met with `JSON-RPC` error
![image](https://user-images.githubusercontent.com/54227730/135177611-cb6b149f-66ca-45b1-968d-b799358270b6.png)

Realized the app state is still in contribution phase, and my contribution did not add to the total on the left. Attempting further contribution transactions gives me that JSON-RPC error.

**Comment by samajammin** [comment]
Thanks for surfacing - we should definitely try to replicate this.

**Comment by wackerow** [comment]
Update from my end: This issue spontaneously resolved after about 1-2 days. I returned to the front-end, with the same wallet, and everything was showing appropriately as the reallocation phase. I was able to reallocate without any problems.

Just re-tested this flow from the beginning with a fresh account and had no issues, unable to replicate above issue. This may have resolved after progress to the subgraph was made. Sounds like @pettinarip did the same without being able to replicate as well, so will close this issue for now. 

If anyone notices this again, please expand `data` section of error log, post here and reopen.
