### ISSUE TITLE
Wrapping issues on mobile summary

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#41]
![image](https://user-images.githubusercontent.com/40891631/117423144-4bc1cc80-af18-11eb-8887-a6cec5a64ca3.png)

**Comment by samajammin** [comment]
![Image 2021-05-11 at 9 52 23 AM](https://user-images.githubusercontent.com/8097623/117854767-a885f580-b23e-11eb-9822-626b8eababd8.jpg)
