### ISSUE TITLE
Button's dont go active on mobile even if form inputs are complete

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#42]
![image](https://user-images.githubusercontent.com/40891631/117423932-27b2bb00-af19-11eb-98ce-3a2bc7b6b7f3.png)

**Comment by ryancreatescopy** [comment]
I actually think in general that buttons don't work on mobile at all.

**Comment by wackerow** [comment]
A fix for this has been merged into `develop`
