### ISSUE TITLE
Etherscan icons/tooltip copy is hardcoded

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#427]
![image](https://user-images.githubusercontent.com/54227730/136093395-8135c661-57a9-496b-8375-a38142f0578b.png)

We use `.env` variables to determine which block explorer to use for links, but we have hardcoded the use of an Etherscan icon and "View on Etherscan" tooltip copy. In the case of the eth2 round, this should be the [Arbitrum explorer](https://explorer.arbitrum.io/) with an icon like this (just smaller, and grayscale):
![arbitrum icon](https://explorer.arbitrum.io/images/Arbitrum_Symbol_-_Full_color_-_White_background.svg)

**Comment by samajammin** [comment]
Circling back on conversation with @wackerow @pettinarip - we should add this to the chain constants info.
