### ISSUE TITLE
Generalize the round criteria

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#430]
Currently our recipient round criteria (https://eth2clrfund.netlify.app/#/join) is built specifically for the Eth2 round - we should generalize the functionality for any clr.fund instance:

![image](https://user-images.githubusercontent.com/8097623/136100423-cf213254-7e7c-4664-9da8-89947f7406f4.png)

What's the best approach here? Should this feed from the deployer application somehow? Should this data live on the FundingRound smart contract? Or should any instance/fork just add their own criteria via HTML? Maybe we reference some IPFS hash from the registry contract?

Here's the current code: https://github.com/ethereum/clrfund/blob/develop/vue-app/src/components/CriteriaModal.vue

**Comment by samajammin** [comment]
@daodesigner @auryn-macmillan keen to get your thoughts on approach here. Perhaps there's already a plan with the deployer to solve these kind of instance-specific content? Thanks in advance 😄

**Comment by auryn-macmillan** [comment]
Ideal case, this should be configurable in the deployer or in some admin view in the app.

**Comment by daodesigner** [comment]
There is a metadata field built in to the deployer subgraph in proxy factory, need to identify all the areas this applies to to see if it's reasonable to store it all on chain events and pull from the subgraph to feed the UI.

**Comment by samajammin** [comment]
Ok sounds good @daodesigner - please keep us posted.

In the meantime @wackerow isolated the round criteria into a standalone file, so at least it's easy for a project to fork & customize for their needs: https://github.com/ethereum/clrfund/blob/develop/vue-app/src/plugins/round/criteria.ts

**Comment by samajammin** [comment]
Marking as solved in #443 - at least now we have a simple criteria file that can easily be edited: https://github.com/ethereum/clrfund/blob/develop/vue-app/src/plugins/round/criteria.ts
