### ISSUE TITLE
Revert changes to OptimisticRecipientRegistry contract

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#432]
We made some changes built specifically for the Eth2 round - we should generalize the functionality for any clr.fund instance.

Investigate history of changes made to this contract:
https://github.com/ethereum/clrfund/commits/develop/contracts/contracts/recipientRegistry/OptimisticRecipientRegistry.sol

I believe the primary steps are:
- [x] Remove owner `onlyOwner` for removing recipients/projects via `removeRecipient`
- [x] Confirm if FE changes are needed/wanted on all clr.fund instances? Check vue-app/src/api/recipient-registry-optimistic.ts

Let's confirm with clr.fund team what desired functionality is here.

**Comment by samajammin** [comment]
For instance, in our Eth2 fork, we're not even using the challenge period. This requires a bit of investigation in terms of what we want to change back here.

**Comment by pettinarip** [comment]
Done.
