### ISSUE TITLE
Update MACI scripts to support subgraph input

### ISSUE THREAD

**Issue by pettinarip** [ethereum/clrfund#434]
Update MACI script (`genProofs`) to accept a subgraph as an input and query events from there.

**Comment by samajammin** [comment]
@pettinarip can this be closed out? Or should we wait until the branch is merged in MACI?

**Comment by samajammin** [comment]
^Ignore that issue I mentioned, I linked to the wrong issue.

**Comment by pettinarip** [comment]
> @pettinarip can this be closed out? Or should we wait until the branch is merged in MACI?

I think we can leave this ticket open until we can confirm that we can run the `proveOnChain` script, and basically until we can finalise a round in Arbitrum.

**Comment by pettinarip** [comment]
This was tested and you can run the scripts using [maci](https://github.com/appliedzkp/maci)@v0.10.1
