### ISSUE TITLE
Dropdown menu persisting after click-away

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#437]
## Description
Dropdown menu at the top of the app is persisting as open even after clicking away, requiring a click on the actual Help button again. This can cause issues if the user opens other features before closing.

## Steps to reproduce:
1. Go to https://eth2clrfund.netlify.app/#/
2. Open the ? menu in the upper right
3. Then connect wallet, noting it does not close
4. Then open Profile by clicking on your address in upper right

This leaves you with the menu open with no way to close it, since the close button is now blocked by the profile.

## Screenshot
![image](https://user-images.githubusercontent.com/54227730/136636722-fe0b6c69-4768-4cb1-93cf-d68ab24e73cb.png)

## Thoughts
Check the logic on how the dropdown menu is triggered to close. Should be closed when clicking anywhere, either outside the dropdown or if a link is selected.

**Comment by corwintines** [comment]
Going to close this, solved in recent PR https://github.com/ethereum/clrfund/pull/475
