### ISSUE TITLE
Recipient application: tagline duplicate validation bug

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#44]
https://www.notion.so/efdn/Recipient-application-tagline-duplicate-validation-bug-2d52196b6cd046b784be94c6dfc1b333

![image](https://user-images.githubusercontent.com/40891631/117432331-2639c080-af22-11eb-83f6-be7fa4cd9382.png)
It shouldn't be possible to get both errors :)

**Comment by ryancreatescopy** [comment]
@wackerow we need to look at this still as it's confusing af.

**Comment by samajammin** [comment]
@wackerow has this been fixed?
