### ISSUE TITLE
Wrap behavior when copying tx hash

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#462]
The address pill component should stay below vs. unwrapping on click:

https://user-images.githubusercontent.com/8097623/145306456-3170d95e-e36e-4159-919d-01783932b9ef.mp4

**Comment by samajammin** [comment]
Separate consideration - should we include a link to open that tx in a block explorer (vs. merely copying the tx hash)?

**Comment by corwintines** [comment]
I would be in favor of a link.
