### ISSUE TITLE
Contribution with zero values like `0.0`

### ISSUE THREAD

**Issue by pettinarip** [ethereum/clrfund#469]
On the contribution form, `0.0` is throwing a validation error. It should be accepted as `0` when submitted.

**Comment by samajammin** [comment]
I don't think _either_ `0.0` or `0` should be accepted in the initial contribution. Is there any advantage to this? Seems like it would just create additional messages in MACI with no purpose.

Can confirm `0.0` or `.00` already shows invalid:
![Image 2021-12-13 at 2 13 36 PM](https://user-images.githubusercontent.com/8097623/145897478-f2b3302e-3a71-4c71-91d3-22e68193a3ed.jpg)



But `0` displays as valid:
![Image 2021-12-13 at 2 13 43 PM](https://user-images.githubusercontent.com/8097623/145897347-53ef4c5e-f1c3-440d-b9c8-216510752cd0.jpg)
