### ISSUE TITLE
Consolidate network token logic?

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#492]
Noticing we use the `getNetworkToken` in a few places:
https://github.com/ethereum/clrfund/blob/develop/vue-app/src/utils/networks.ts

But in other spots we rely on the `currency` value of chain info:
https://github.com/ethereum/clrfund/blob/develop/vue-app/src/plugins/Web3/constants/chains.ts

**Comment by samajammin** [comment]
Context / decision related to this, I'm wondering if we should specifically reference Arbitrum ETH as `arbETH` vs `ETH` to avoid any potential confusion across the app.

**Comment by corwintines** [comment]
Since we only use getNetworkToken in one spot (https://github.com/ethereum/clrfund/blob/develop/vue-app/src/api/recipient-registry-optimistic.ts) I propose we just get rid of it in favor of the chain.currency method.
