### ISSUE TITLE
ClaimButton hangs with loading spinner

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#499]
When running the web app locally (`yarn start:web`) w/ the test round Arbitrum One env variables, I'm seeing a loading spinner instead of the ClaimButton (no console errors):

![Image 2022-01-10 at 2 15 06 PM](https://user-images.githubusercontent.com/8097623/148847741-fd625d5f-d982-4e09-8dd8-3ec97f5eccfd.jpg)

@pettinarip mind checking if you can replicate this? Not sure why this is occurring.

**Comment by pettinarip** [comment]
This is caused by not uploading the tally file to ipfs. This loading spinner is fetching that file that doesn't exist.

In this test, I had uploaded it to ipfs but now it seems that no one is serving it anymore (I was the only one at that moment).
