### ISSUE TITLE
Scroll position not resetting to top w/ internal links

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#52]
On mobile, noted that scrolling down a page, then tapping an internal link, does not refresh the the scroll position to top when the new view loads:
![image](https://user-images.githubusercontent.com/54227730/117874303-a54a3400-b255-11eb-89da-48375676be2b.png)
![image](https://user-images.githubusercontent.com/54227730/117874318-abd8ab80-b255-11eb-80d5-af2c81ef141f.png)

**Comment by ryancreatescopy** [comment]
Fixed in #66
