### ISSUE TITLE
Landing page height should take RoundStatusBanner into account

### ISSUE THREAD

**Issue by samajammin** [ethereum/clrfund#53]
For the landing pages (e.g. JoinLanding) that we want full height, we should adjust for the RoundStatusBanner.

Currently it creates this awkward scroll where the banner gets cut off:
https://user-images.githubusercontent.com/8097623/117903589-b3fc0f80-b284-11eb-903c-2fa8a3c5cfd0.mp4

**Comment by wackerow** [comment]
@samajammin I believe changes in #26 now take care of this, let me know if you're getting this on that PR as well

**Comment by samajammin** [comment]
Ok nice I'll check that out

**Comment by ryancreatescopy** [comment]
@samajammin @wackerow is this done?

**Comment by samajammin** [comment]
Yep 👍
