### ISSUE TITLE
recipient address doesn't copy or go to etherscan

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#63]
![image](https://user-images.githubusercontent.com/40891631/118287367-4c83d100-b4cb-11eb-898c-80627e2cc970.png)

the buttons are dummy right now

**Comment by ryancreatescopy** [comment]
@wackerow mind taking a look at this?

**Comment by samajammin** [comment]
We may want to address this in tandem with https://github.com/ethereum/clrfund/issues/83
