### ISSUE TITLE
Join transaction doesn't always recognise security deposit

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#68]
While I was working on the join transaction styling, occasionally it would load without all the information and the tx wouldn't work. I wonder whether this is complications from HardHat local chain. But either way this should be investigated.

![image](https://user-images.githubusercontent.com/40891631/118632141-09c24180-b7c8-11eb-8943-7185e0359aab.png)

**Comment by ryancreatescopy** [comment]
@samajammin @wackerow bringing your attention to this...

**Comment by samajammin** [comment]
@samajammin to confirm this has been fixed when we added recipient info fetching to store (#56)

**Comment by wackerow** [comment]
@samajammin Have you seen this error moving forward? I have not

**Comment by samajammin** [comment]
Haven't been able to replicate, closing for now.
