### ISSUE TITLE
RoundInfo broken on tablet sizes

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#70]
Should stack like on mobile
![image](https://user-images.githubusercontent.com/40891631/118784511-fc6c8c00-b887-11eb-96b4-f3a192c3937f.png)

**Comment by ryancreatescopy** [comment]
iphoneX:
![image](https://user-images.githubusercontent.com/40891631/118784578-0c846b80-b888-11eb-93da-eb0716b43b44.png)

**Comment by samajammin** [comment]
@samajammin to confirm this was fixed in https://github.com/ethereum/clrfund/pull/66

**Comment by samajammin** [comment]
Confirming this has been fixed.
