### ISSUE TITLE
Display project thumbnail, title and link in walletwidget

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#73]
https://www.notion.so/efdn/Display-project-thumbnail-title-and-link-in-walletwidget-7d046a28d5fd43cd8eb0275d65d23915

If currentUser is a recipient, we want to display project info/status in the WalletWidget component.

![image](https://user-images.githubusercontent.com/40891631/119126808-6e310b00-ba2b-11eb-8a36-510c63218b53.png)

We should display project information if the connected wallet is the `signer` for any projects in the round. 

Maybe we could even display a status for users...

example design:
![image](https://user-images.githubusercontent.com/40891631/119126846-7d17bd80-ba2b-11eb-9cc4-dd2c73568004.png)

**Comment by samajammin** [comment]
Marking as a low priority - this is a "nice to have"

**Comment by samajammin** [comment]
We should also hide the "Projects" header unless the user has a project in the round.
