### ISSUE TITLE
Remove register button from projectCard / projectPage

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#74]
If admins are going to be approving/registering projects from `recipients` we don't need a register button on the projectCards/projectPage
- [x] remove "register" button from project page & ProjectListItem component

Only registered projects should be visible in the projectList... 
- [x] confirm we only list registered projects

NOTE: they should still have a url so that admins can review their page before registering them... Maybe this means we should retain the button on the ProjectPage...

**Comment by ryancreatescopy** [comment]
being worked on in #86

**Comment by corwintines** [comment]
@samajammin just want to check, in the `ProjectList` component visible projects are currently filtered by:

`const visibleProjects = projects.filter((project) => {
      return !project.isHidden && !project.isLocked
    })`

Just want to check that this is how registered projects should be filtered. Seems to be the only items on projects that I could see for easily filtering them, but if there is something else to do this maybe we can pair up for a moment just to educate me.

**Comment by wackerow** [comment]
This appears to be fixed with #174... closing for now... @corwintines please reopen if I'm missing something =)
