### ISSUE TITLE
Remove input / contribute CTA from projectCard / projectPage when necessary

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#75]
if user has contributed:
- when reallocation phase is over this is no longer necessary

if user hasn't contributed:
- after contribution phase, this CTA is no longer necessary

if user is unconnected and it's during the reallocation phase:
- show the CTA in case they have contributed. 
- pressing the CTA should trigger the wallet connection
- once they're connected we can detect an if they never contributed we can display an error message in a modal

Question: do we replace or remove? We could replace with a "Too late to add to cart" message. However this might be a lot of content and maybe the cart state can explain this.

**Comment by ryancreatescopy** [comment]
Believe this is being tackled in #86

**Comment by ryancreatescopy** [comment]
Fixed by #111

**Comment by samajammin** [comment]
Confirmed - solved in #111
