### ISSUE TITLE
Validation for cart inputs

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#78]
![image](https://user-images.githubusercontent.com/40891631/119147272-55ccea80-ba43-11eb-85f0-43759a6d5509.png)

You shouldn't be able to add anything but numbers to the cart inputs. 

Can we prevent non-integer inputs or do we need to validate (disable buttons/error message etc.)

**Comment by ryancreatescopy** [comment]
I believe we get an error message at the bottom of the cart currently...

```
} else if (!this.isFormValid()) {
      return 'Please enter correct amounts'
```

do we need in-line validation?

**Comment by samajammin** [comment]
Agreed, we should create inline error handling for these inputs. Better yet, we should force these to be number inputs so any invalid characters are prevented from ever being input.

**Comment by samajammin** [comment]
On a related note, we display this `Only numbers in your contributions please` error if the user inputs an amount with >5 decimals:

https://user-images.githubusercontent.com/8097623/122275613-c0354700-ce98-11eb-9aed-48e3fbafb3c5.mp4

We should restrict the input values to:
1. only allow integers
2. enforce a limit of 5 decimal places

**Comment by samajammin** [comment]
This relates to the issue I mentioned here: https://github.com/ethereum/clrfund/pull/150#issuecomment-862623694
