### ISSUE TITLE
Cart CTA hover bug

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#80]
Hovering on the cart button shouldn't clip the left edge like it does right now...
https://user-images.githubusercontent.com/40891631/119320670-bc384f80-bc73-11eb-84eb-9b434ceb4bc1.mov

It should behave more like this... however also shouldn't force project list content over
https://user-images.githubusercontent.com/40891631/119320719-c78b7b00-bc73-11eb-9563-9e32c9ff0285.mov

**Comment by wackerow** [comment]
Possibly fixed now with commit 82c99ba on #66.
