### ISSUE TITLE
If time less than a minute, show minutes/seconds not hours

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#84]
https://www.notion.so/efdn/Create-general-countdown-utility-function-timer-28ab69b08fba4360a691ab6257421f7f

![image](https://user-images.githubusercontent.com/40891631/119454761-ca987100-bd30-11eb-813a-5116ef488591.png)

If more than 24 hours... show x day y hours
if less than 24 hours... show x hours 7 minutes
if less than 1 hour should x minutes
if less than 1 minute show x seconds

where we show seconds we'll need it to countdown

This will likely involve updating the `getTimeLeft` function to display differently if time is <1 minute.

**Comment by samajammin** [comment]
Agreed - nice to have though, marking as lower priority.

**Comment by samajammin** [comment]
Closely related to #234 - perhaps we create a generalized utility function that we use everywhere?
