### ISSUE TITLE
ProjectListItem style & logic updates

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#93]
![image](https://user-images.githubusercontent.com/40891631/119852815-890dee80-bf07-11eb-99e8-a3fcb6dfe72d.png)

- [x] a user can't contribute to a project before it's been registered (#74 will ensure we only display registered projects)
- [x] we should hide ability to contribute if this isn't possible (fixed in #111)
- [x] When a project is able to claim, they should see that button - confirm this uses up-to-date button styles
- [x] Confirm the register button has been removed

**Comment by samajammin** [comment]
- [ ] @samajammin figure our which PR addresses this (if any)
- [ ] confirm ProjectListItem also has claim button after round has been finalized
- [ ] check ProjectListItem image is resized to fit the space on the card
