### ISSUE TITLE
Contribution tx modal bug

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#94]
https://www.notion.so/efdn/Contribution-tx-modal-bug-491adf6b1d3d464d84e2a83bdb10e6d6

If you get 1/3 of the way through the contribution transactions and come back, you shouldn't get the initial warning again. This warning should only appear if you haven't already signed 'approve' transaction. It's too late if you've already approved the token amount...

- [ ] @samajammin investigate at what point it's irreversible (I believe not until the contribution tx, i.e. in theory you could execute multiple approvals if you cancel this flow & add more items to your cart)

https://user-images.githubusercontent.com/40891631/119985610-c67f8400-bfba-11eb-9492-15e9085b63a4.mov

**Comment by ryancreatescopy** [comment]
I guess you also shouldn't be able to edit your cart?

Alternatively, perhaps you can re-approve if you cancel out after approval transaction?

Thoughts @samajammin ??

**Comment by samajammin** [comment]
Added an item to investigate if use can submit to re-approve amounts (I believe you can).

Assuming that's possible... can we query smart contract or local store data to determine what step a user is on (e.g. if they canceled this modal & return to it later)? This will also require some investigation.
- We should be able to query the approval amount to see if the cart amount matches the token amount the contract has the ability to transfer
- We _should_ be able to query if the contribution tx has happened (e.g. by looking at the Contribution event on the smart contract to see if an event has been emitted w/ the current address)
- Can we somehow check to see if the current address has already voted or not (i.e. `fundingRound.submitMessageBatch`)?

**Comment by pettinarip** [comment]
This issue is closely related to #212.

We need a way to open the `ContributionModal` in specific steps. Right now, we are doing all contribution steps straight forward. 

When we have identified/added that specific state in the store, we are gonna be able to easily display the #212 warning messages to the user (in the Cart).

**Comment by corwintines** [comment]
Closing this as it was solved in the above merged PR
