### ISSUE TITLE
RoundInfo bugs

### ISSUE THREAD

**Issue by ryancreatescopy** [ethereum/clrfund#95]
![image](https://user-images.githubusercontent.com/40891631/120322102-f214ae00-c2db-11eb-9708-915afc761b61.png)

- [ ] total in round just puts two numbers together Total + Matching pool - it should display the sum (e.g. it should be 560 AOE) - this is probably an issue with concatenating string values vs. converting to numbers to perform sum operations.
- [x] Weird size number after decimal in contributions total
- [ ] Legends shouldn't pluralise if 1 contibutor.

**Comment by samajammin** [comment]
A related bug:

![Image 2021-06-01 at 3 06 55 PM](https://user-images.githubusercontent.com/8097623/120396355-470bf080-c2eb-11eb-8804-67844fb13e95.jpg)

- [x] When reallocation stage is over, we should hide the "time left to reallocate" section.

**Comment by ryancreatescopy** [comment]
Thought I had fixed this. Can't reproduce this as can't get through the transaction now on `develop` :(

**Comment by ryancreatescopy** [comment]
Update: there seems to be no rhyme/reason but sometimes transactions don't work and other times they're fine...

**Comment by samajammin** [comment]
Solved in #108 & #107
