### ISSUE TITLE
Trash can hover glitch

### ISSUE THREAD

**Issue by wackerow** [ethereum/clrfund#97]
![image](https://user-images.githubusercontent.com/54227730/120391332-b67de200-c2e3-11eb-9f11-a3602956fe54.png)

Hover over trash icon steals z-index focus from dropdown menu, placing trash can above it (when they collide)

**Comment by corwintines** [comment]
@wackerow are you still noticing this? I went to go work on this, and seems to be working properly.
<img width="226" alt="Screen Shot 2021-06-03 at 11 28 42 AM" src="https://user-images.githubusercontent.com/15589226/120687108-ea314700-c45e-11eb-9104-c395a28e9335.png">

Let me know, I can come back to this, but seems like maybe something sorted itself out, or I might need to pair with you for a second to replicate. Thanks.

**Comment by ryancreatescopy** [comment]
Fixed by #121
